import "@fontsource/comic-mono"; // Defaults to weight 400
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-neutral-900 text-neutral-50 h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}
